In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

#pip install scikit-learn

In [2]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
df=pd.read_csv("1.csv")  
print(df)

FileNotFoundError: [Errno 2] No such file or directory: '1.csv'

In [ ]:
%matplotlib inline
plt.xlabel("ar")
plt.ylabel("price")
plt.scatter(df.area,df.price,color="red")
plt.show()

In [ ]:
r = linear_model.LinearRegression()
r.fit(df[['area']],df.price)


In [ ]:
p = r.predict([[2600]])
print(p)
plt.plot(df.area,r.predict(df[['area']]))

In [ ]:
print(r.coef_)
print(r.intercept_)

In [ ]:
'''r.coef_ #gives the value of coeffiecent from equation i.e y=mx+b  the value of m 
r.intercept_     #gives the value of b '''


In [ ]:

d=pd.read_csv("2.csv")
d



In [ ]:

p=r.predict(d)

In [ ]:
p

In [ ]:
d['prices']=p
d.to_csv('lalit',index=False)

In [ ]:
g=pd.read_csv('lalit')

In [ ]:
g

In [ ]:
plt.plot(df.area,r.predict(df[['area']]))

In [4]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [5]:
df=pd.read_csv("3.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: '3.csv'

In [ ]:
df.bedrooms.median()

In [ ]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)
reg

In [ ]:
reg.coef_
reg.intercept_
reg.predict([[5000,50,78]])

In [ ]:
#########################    EXERCISE    ######################################

In [6]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
df=pd.read_csv("exercise.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'exercise.csv'

In [ ]:
df.test_score.median()

In [ ]:
df.test_score=df.test_score.fillna(df.test_score.median())
df

In [ ]:
%pip install word2number


In [ ]:
from word2number import w2n

df["experience"] = df["experience"].apply(
    lambda x: w2n.word_to_num(x) if isinstance(x, str) else x
)

df


In [7]:
re = linear_model.LinearRegression()
re.fit(df[['experience','test_score','interview_score']],df.salary)
re.predict([[7,6,6]])

NameError: name 'df' is not defined

In [ ]:
re.predict([[12,10,10]])

In [ ]:
%matplotlib inline
plt.xlabel("score")
plt.ylabel("salary")
plt.plot(df.interview_score,df.salary,color="yellow")


In [ ]:
%matplotlib inline
plt.xlabel("score")
plt.ylabel("salary")
plt.stackplot(df.interview_score,df.salary,color="yellow")


In [ ]:
%matplotlib inline
plt.xlabel("score")
plt.ylabel("salary")
plt.scatter(df.interview_score,df.salary,color="yellow")


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.linear_model import LinearRegression
import numpy as np

X = df[['experience','test_score','interview_score']]
y = df['salary']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R2 Score:", r2)
print("MAE:", mae)
print("RMSE:", rmse)


In [ ]:
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(re,f)

In [ ]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)
mp.predict([[3,5,78]])

In [2]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error 

In [3]:
tips = sns.load_dataset('tips')
pip install scikit-learn

In [5]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [6]:
x = tips[['total_bill']]
y = tips['tip']

In [22]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42) 

In [23]:
model = LinearRegression()
model.fit(x_train , y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [24]:
pred = model.predict(x_test)

In [25]:
mse = mean_squared_error(y_test ,pred )

mse

In [26]:
mse

0.5688142529229538

In [27]:
data = pd.read_csv("Salary_dataset.csv")

In [28]:
data.head()

,Unnamed: 0,YearsExperience,Salary
0,0,1.2,39344.0
1,1,1.4,46206.0
2,2,1.6,37732.0
3,3,2.1,43526.0
4,4,2.3,39892.0


In [33]:
input=  data[['YearsExperience']]
output = data['Salary']

In [35]:
input.head()

,YearsExperience
0,1.2
1,1.4
2,1.6
3,2.1
4,2.3


In [36]:
output.head()

0    39344.0
1    46206.0
2    37732.0
3    43526.0
4    39892.0
Name: Salary, dtype: float64

In [37]:
x_train , x_test , y_train , y_test = train_test_split(input , output , test_size = 0.2 , random_state = 42)

In [38]:
lin = LinearRegression()

In [39]:
lin.fit(x_train , y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [51]:
te = lin.predict([[5]])
te

C:\Users\Dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([71499.27809463])

m = mean_squared_error(y_test , te)

In [42]:

m = mean_squared_error(y_test , te)

In [44]:
m

49830096.855908334

In [45]:
lin.coef_

array([9423.81532303])

In [46]:
lin.intercept_

np.float64(24380.20147947369)

In [47]:
model.coef_

array([0.10696371])

In [49]:
model.intercept_

np.float64(0.9252355585570546)